# Generated by Django 5.0.1 on 2024-01-10 19:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('vehicle', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='vehicle',
            name='owner',
        ),
        migrations.DeleteModel(
            name='Profile',
        ),
    ]
